export const teeth = [
  [
    {
      tooth: 18,
      class: 'mirror-x',
      style: 'margin: 0 3px',
      src: 'tm-3.png',
    },
    {
      tooth: 17,
      class: 'mirror-x',
      style: 'margin: 0 -1px',
      src: 'tm-2.png',
    },
    {
      tooth: 16,
      class: 'mirror-x',
      style: '',
      src: 'tm-1.png',
    },
    {
      tooth: 15,
      class: 'mirror-x',
      style: 'margin: 0 -9px',
      src: 'tp-2.png',
    },
    {
      tooth: 14,
      class: 'mirror-x',
      style: 'margin: 0 -5px',
      src: 'tp-1.png',
    },
    {
      tooth: 13,
      class: 'mirror-x',
      style: 'margin: 0 -11px',
      src: 'tk.png',
    },
    {
      tooth: 12,
      class: 'mirror-x',
      style: 'margin: 0 -5px',
      src: 'tbr.png',
    },
    {
      tooth: 11,
      class: 'mirror-x',
      style: 'margin: 0 -10px',
      src: 'tcr.png',
    },
    {
      tooth: 21,
      class: '',
      style: 'margin: 0 -5px',
      src: 'tcr.png',
    },
    {
      tooth: 22,
      class: '',
      style: 'margin: 0 -10px',
      src: 'tbr.png',
    },
    {
      tooth: 23,
      class: '',
      style: 'margin: 0 -7px',
      src: 'tk.png',
    },
    {
      tooth: 24,
      class: '',
      style: 'margin: 0 -10px',
      src: 'tp-1.png',
    },
    {
      tooth: 25,
      class: '',
      style: 'margin: 0 -8px 0 -5px',
      src: 'tp-2.png',
    },
    {
      tooth: 26,
      class: '',
      style: '',
      src: 'tm-1.png',
    },
    {
      tooth: 27,
      class: '',
      style: '',
      src: 'tm-2.png',
    },
    {
      tooth: 28,
      class: '',
      style: 'margin: 0 3px',
      src: 'tm-3.png',
    },
  ],
  [
    {
      tooth: 48,
      class: 'mirror-x',
      style: 'margin: 0',
      src: 'bm-3.png',
    },
    {
      tooth: 47,
      class: 'mirror-x',
      style: 'margin: 0 0px 0 -2px',
      src: 'bm-2.png',
    },
    {
      tooth: 46,
      class: 'mirror-x',
      style: '',
      src: 'bm-1.png',
    },
    {
      tooth: 45,
      class: 'mirror-x',
      style: 'margin: 0 -6px',
      src: 'bp-2.png',
    },
    {
      tooth: 44,
      class: 'mirror-x',
      style: 'margin: 0 -9px',
      src: 'bp-1.png',
    },
    {
      tooth: 43,
      class: 'mirror-x',
      style: 'margin: 0 -7px',
      src: 'bk.png',
    },
    {
      tooth: 42,
      class: 'mirror-x',
      style: 'margin: 0 -12px',
      src: 'bbr.png',
    },
    {
      tooth: 41,
      class: 'mirror-x',
      style: 'margin: 0 -8px',
      src: 'bcr.png',
    },
    {
      tooth: 31,
      class: '',
      style: 'margin: 0 -12px',
      src: 'bcr.png',
    },
    {
      tooth: 32,
      class: '',
      style: 'margin: 0 -8px',
      src: 'bbr.png',
    },
    {
      tooth: 33,
      class: '',
      style: 'margin: 0px -13px 0 -11px;',
      src: 'bk.png',
    },
    {
      tooth: 34,
      class: '',
      style: 'margin: 0 -1px 0 -3px',
      src: 'bp-1.png',
    },
    {
      tooth: 35,
      class: '',
      style: 'margin: 0 -6px 0 -15px',
      src: 'bp-2.png',
    },
    {
      tooth: 36,
      class: '',
      style: 'margin: 0 -2px 0 -3px',
      src: 'bm-1.png',
    },
    {
      tooth: 37,
      class: '',
      style: '',
      src: 'bm-2.png',
    },
    {
      tooth: 38,
      class: '',
      style: 'margin: 0 -1px',
      src: 'bm-3.png',
    },
  ],
]

export const teeth_ten = [
  [
    {
      tooth: 55,
      class: 'mirror-x',
      style: '',
      src: 'tm-2.png',
    },
    {
      tooth: 54,
      class: 'mirror-x',
      style: '',
      src: 'tm-1.png',
    },
    {
      tooth: 53,
      class: 'mirror-x',
      style: 'margin: 0 -9px',
      src: 'tk.png',
    },
    {
      tooth: 52,
      class: 'mirror-x',
      style: 'margin: 0 -7px',
      src: 'tbr.png',
    },
    {
      tooth: 51,
      class: 'mirror-x',
      style: 'margin: 0 -8px',
      src: 'tcr.png',
    },
    {
      tooth: 61,
      class: '',
      style: 'margin: 0 -6px',
      src: 'tcr.png',
    },
    {
      tooth: 62,
      class: '',
      style: 'margin: 0 -9px',
      src: 'tbr.png',
    },
    {
      tooth: 63,
      class: '',
      style: 'margin: 0 -9px 0 -7px',
      src: 'tk.png',
    },
    {
      tooth: 64,
      class: '',
      style: '',
      src: 'tm-1.png',
    },
    {
      tooth: 65,
      class: '',
      style: '',
      src: 'tm-2.png',
    },
  ],
  [
    {
      tooth: 85,
      class: '',
      style: '',
      src: 'bm-2.png',
    },
    {
      tooth: 84,
      class: '',
      style: '',
      src: 'bm-1.png',
    },
    {
      tooth: 83,
      class: '',
      style: 'margin: 0 -7px',
      src: 'bk.png',
    },
    {
      tooth: 82,
      class: '',
      style: 'margin: 0 -12px',
      src: 'bbr.png',
    },
    {
      tooth: 81,
      class: '',
      style: 'margin: 0 -5px 0 -8px',
      src: 'bcr.png',
    },
    {
      tooth: 71,
      class: '',
      style: 'margin: 0 -14px',
      src: 'bcr.png',
    },
    {
      tooth: 72,
      class: '',
      style: 'margin: 0 -6px',
      src: 'bbr.png',
    },
    {
      tooth: 73,
      class: '',
      style: 'margin: 0 -7px 0 -13px',
      src: 'bk.png',
    },
    {
      tooth: 74,
      class: '',
      style: '',
      src: 'bm-1.png',
    },
    {
      tooth: 75,
      class: '',
      style: '',
      src: 'bm-2.png',
    },
  ],
]
